### ISSUE TITLE
Model settings and template interactions

### ISSUE THREAD

**Issue by jwsmith24** [jwsmith24/palette#119]
Design the settings and template functionality to be stored locally on the backend server

![Image](https://github.com/user-attachments/assets/ae4b56c6-f1f6-4d28-bd53-4f1629927d83)

**Comment by benaspinall1** [comment]
![Image](https://github.com/user-attachments/assets/538a6f3c-6441-4b39-99d1-d241d1e052db)

**Comment by benaspinall1** [comment]
![Image](https://github.com/user-attachments/assets/a08f689d-232f-4697-8644-f8c84effd8a3)
