### ISSUE TITLE
log data is displayed from api endpoint

### ISSUE THREAD

**Issue by jwsmith24** [jwsmith24/palette#45]
Found this while messing around with testing. We should probably hide log data from showing

![image](https://github.com/user-attachments/assets/ad59ecdb-48db-4554-b05e-8345165088ca)

**Comment by jwsmith24** [comment]
although this might not even be an issue once we close down our allowed ports in the CORS middleware

**Comment by cmccand1** [comment]
You haven't already started testing the backend have you? I've got a refactoring idea for it

**Comment by jwsmith24** [comment]
Nope! Let's hear it 🚀
