### ISSUE TITLE
`Add Description` default text rendering on rubric ratings

### ISSUE THREAD

**Issue by cmccand1** [jwsmith24/palette#87]
It is also being sent on the rubric if no text is actually entered in its field
<img width="671" alt="Screenshot 2024-11-11 at 4 17 18 AM" src="https://github.com/user-attachments/assets/1cd13976-498d-4545-bb39-bf61270bf3d2">

**Comment by jwsmith24** [comment]
I need to look at the csv template more closely! 

Will likely add a check to not even display the "long description" if it's not present

**Comment by jwsmith24** [comment]
See demo of the UI updates in [slack](https://asu.enterprise.slack.com/archives/C07M17KRRNG/p1731780812546539)
