### ISSUE TITLE
Importing CSV's with "placeholder" ratings triggers backend rubric validation error

### ISSUE THREAD

**Issue by cmccand1** [jwsmith24/palette#88]
<img width="609" alt="Screenshot 2024-11-11 at 4 25 12 AM" src="https://github.com/user-attachments/assets/39682743-46f4-4977-9fae-69a412595ea0">
<img width="730" alt="Screenshot 2024-11-11 at 4 25 29 AM" src="https://github.com/user-attachments/assets/aaf687f2-68b1-4eba-b96e-3ee639d69303">
<img width="893" alt="Screenshot 2024-11-11 at 4 26 11 AM" src="https://github.com/user-attachments/assets/5459ef34-c56c-48a9-8dac-8a7f086141a3">

**Comment by jwsmith24** [comment]
Looks like you added the optional check to the validator! Able to add rubrics with freshly generated criteria without issue.
